# Copyright (c) CloudBees, Inc.

#https://artifacthub.io/packages/helm/vmware-tanzu/velero
#https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml

kubectl:
  image:
    #Issue #60
    tag: 1.26.14-debian-11-r6

initContainers:
- name: inject-metadata-velero-plugin
  image: ghcr.io/cloudbees-oss/inject-metadata-velero-plugin:main
  imagePullPolicy: Always
  volumeMounts:
  - mountPath: /target
    name: plugins
