# Copyright (c) CloudBees, Inc.
---
name: "Code Quality: Terraform"

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.yaml'
      - '**.yml'

env:
  TFLINT_VERSION: v0.44.1
  TERRAFORM_VERSION: v1.6.6 #Keep aligment with the agent version

jobs:
  preCommit:
    name: TF pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pre-commit Terraform Validate ${{ env.TERRAFORM_VERSION }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
        with:
            terraform-version: ${{ env.TERRAFORM_VERSION }}
            args: 'terraform_validate'
      - name: Pre-commit Terraform Format ${{ env.TERRAFORM_VERSION }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
        with:
            terraform-version: ${{ env.TERRAFORM_VERSION }}
            args: 'terraform_fmt'
      - name: Pre-commit Terraform TFLint ${{ env.TERRAFORM_VERSION }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
        with:
            terraform-version: ${{ env.TERRAFORM_VERSION }}
            tflint-version: ${{ env.TFLINT_VERSION }}
            args: 'terraform_tflint'
